### ISSUE TITLE
extraction does not preserve the original timestamps

### ISSUE THREAD

**Issue by spatel-wd** [Galzzly/extract#3]
**Describe the bug**
Using extract utility on talkback..gz and looking at fusion/logs/server/* - timestamps on the files are of current extraction date/time instead of original create/mod timestamp.

If I do "tar xvfz talkback.gz" then it's showing expected timestamps on those log files

**To Reproduce**
1. What type of file was attempted
2. What command was issued
3. What was the output / outcome

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: 

**Additional context**

**Comment by Galzzly** [comment]
Updated extraction for tar and zip, can be found in version 1.1.0 [here](https://github.com/Galzzly/extract/releases/tag/v1.1.0)

Tested possibilities for gzip, bzip2, and rar, however, they did not work and so have not included them in this release.
